name: CICD
on:
  push:
    branches:
      - main
  workflow_dispatch: # allow this workflow to be called by other workflows

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  openapi-lint-checks:
    runs-on: ubuntu-latest
    name: OpenAPI Linter
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 18
      - name: v5 Lint
        run: npx @redocly/cli lint api/v5/openapi.yaml

  deploy-latest-packages:
    if: github.repository_owner == 'guacsec' && !contains(github.event.head_commit.message, 'build(release)')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Java 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Import GPG key for Maven
        run: |
          mkdir -p ~/.gnupg
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build and Publish to Maven Central and NPM registry
        run: |
          # Get the base version and strip -SNAPSHOT for npm
          export BASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//')
          mvn -B deploy --file pom.xml --settings .github/workflows/maven/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          RC_VERSION: ${{ github.run_number }}
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
