name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Custom version (optional)'
        required: false
        type: string

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    if: github.repository_owner == 'trustification'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
          registry-url: 'https://npm.pkg.github.com'

      - name: Remove snapshot
        run: mvn -B versions:set -DremoveSnapshot -DgenerateBackupPoms=false

      - name: Build and Deploy
        run: mvn -B deploy -Ppublish -Prelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        id: get_version
        run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.event.inputs.version || steps.get_version.outputs.version }}
          tag_name: v${{ github.event.inputs.version || steps.get_version.outputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update to next version
        if: success()
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            mvn -B release:update-versions -DnewVersion=${{ github.event.inputs.version }}
          else
            mvn -B release:update-versions
          fi
          # Run the phase that triggers README.md update
          mvn -B validate

      - name: Create Pull Request with next version
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "build(release): update to next development version"
          branch: chore/bump-version
          title: "chore: bump to next development version"
          signoff: true
          body: |
            This PR updates the project to the next development version after the release.
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for the PR
        if: ${{ success() && steps.cpr.outputs.pull-request-number != '' }}
        run: |
          gh pr merge ${{ steps.cpr.outputs.pull-request-number }} --merge --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
